### ISSUE TITLE
Remarks on BulkWalk Method incorrect

### ISSUE THREAD

**Issue by d-herberger** [lextudio/sharpsnmplib#110]
I was having issues with the BulkWalk method.  I brought it up [here](https://stackoverflow.com/questions/54948360/perform-snmp-walk-using-sharpsnmplib-bulkwalk-method).  It appears that the summary param indicate that the 3rd parameter is the community name but in the sample code the code uses the username. 

Recommend updating the summary param.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lextm** [comment]
Fixed in 425bdd8294890ef12e9848533ab0ba89eeedbd1c
