### ISSUE TITLE
IP Type Not Accepting Valid IPv6 Address

### ISSUE THREAD

**Issue by kmiller77** [lextudio/sharpsnmplib#111]
We just started to use IPv6 and I have the need to set an OID with an IPv6 address. The IP type doesn't appear to be accepting a valid IP of 2620:131:101e:402:7968:a298:db56:eeea. Prior to even trying to do the set, I convert to IPAddress to confirm that a valid IP has been sent in. IPAddress parsing confirms it's the proper format IP, but IP.cs throws a format exception "An invalid IP address was specified." on line 119.

**Comment by lextm** [comment]
`IP(string)` only accepts IP v4 strings. If you want to construct an IP v6 object, use `IP(byte[])` instead and pass the raw bytes.

**Comment by kmiller77** [comment]
Ah makes sense! However, when tried that I get another error inside IP.cs. I believe `IP(Tuple<int, byte[]> length, Stream stream)` is only allowed IPv4 but it seems that `CreateSnmpData ` inside DataFactory is calling it

**Comment by lextm** [comment]
I am asking you to use https://github.com/lextudio/sharpsnmplib/blob/master/SharpSnmpLib/IP.cs#L42

**Comment by kmiller77** [comment]
Yes, I understand that and I am. However, to get the responses I'm also using `MessageFactory.ParseMessages` which calls `DataFactory.CreateSnmpData` which in turn calls `IP(Tuple<int, byte[]> length, Stream stream)`

**Comment by kmiller77** [comment]
To clarify, I'm not sure if this is a bug or just a confusing exception message, but this is the code i'm referring to

`if (length.Item1 != IPv4Length)
{
       throw new ArgumentException("Bytes must contain 4 or 16 elements.", nameof(length));
}`

It's only checking for 4 bytes but says it can contain 4 OR 16.

I ended up finding that I can just use an Octet string sending in the IPv6 address bytes (not sure if all OIDs work like that but the one I need did), but I thought that part was a bit confusing

**Comment by lextm** [comment]
I checked previous commit and relevant materials, IP class should not be able to support IPv6 addresses, as the underlying SNMP data type IpAddress only supports v4 addresses.

To store v6 addresses, relevant textual conventions should be used instead,

https://tools.ietf.org/html/rfc2851

and their underlying data type is OCTET STRING.
