### ISSUE TITLE
ILogger and bunch of other classes were removed

### ISSUE THREAD

**Issue by winter3angle** [lextudio/sharpsnmplib#112]
Hi folks! Was using v.10 of your solution, recently I updated the package from nuget and noticed that `ILogger` interface is no more.
This has been deteled in 9349fb68f15c2d3d521fc6feed8584d49cf98dc0
Was it deleted by accident or intentionally?
Seems that there is no documentation changes and any info regarding this.

**Comment by winter3angle** [comment]
Decided to stay on 10.0.11 for a while

**Comment by lextm** [comment]
The relevant namespaces are moved to the samples repo as part release 11.x (the release notes contain that),

https://github.com/lextudio/sharpsnmplib-samples

To use them, you need to compile from the source code.
