### ISSUE TITLE
Lextm.SharpSnmpLib.SnmpException if different community

### ISSUE THREAD

**Issue by dimka59ru** [lextudio/sharpsnmplib#114]
Hi.
If I use read-community on device "public" and in app "public2". I get Exception Lextm.SharpSnmpLib.SnmpException: data construction exception ---> System.ArgumentException: Invalid varbind section data type: Integer32.
What is wrong?

> Вызвано исключение: "Lextm.SharpSnmpLib.SnmpException" в SharpSnmpLib.dll
Lextm.SharpSnmpLib.SnmpException: data construction exception ---> System.ArgumentException: Invalid varbind section data type: Integer32.
Имя параметра: varbindSection
   в Lextm.SharpSnmpLib.Variable.Transform(Sequence varbindSection)
   в Lextm.SharpSnmpLib.ResponsePdu..ctor(Tuple`2 length, Stream stream)
   в Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   --- Конец трассировки внутреннего стека исключений ---
   в Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   в Lextm.SharpSnmpLib.Sequence..ctor(Tuple`2 length, Stream stream)
   в Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   в Lextm.SharpSnmpLib.Messaging.MessageFactory.ParseMessage(Int32 first, Stream stream, UserRegistry registry)
   в Lextm.SharpSnmpLib.Messaging.MessageFactory.ParseMessages(Byte[] buffer, Int32 index, Int32 length, UserRegistry registry)
   в Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, UserRegistry registry, Socket udpSocket)
   в Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, Socket udpSocket)
   в Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver)
   в Lextm.SharpSnmpLib.Messaging.Messenger.Get(VersionCode version, IPEndPoint endpoint, OctetString community, IList`1 variables, Int32 timeout)
   в TFortisDeviceManager.Monitoring.GetUptime(String ip) в D:\Программирование\GitLab\TFortisDeviceManager\TFortisDeviceManager\Monitoring.cs:строка 481

**Comment by lextm** [comment]
I also wonder why. A proper device should return you nothing, as a wrong community name should trigger a time out exception.

**Comment by dimka59ru** [comment]
Ok, I will try to handle the error. Thank you.

**Comment by lextm** [comment]
Before actually trying to handle the error, you should check why there is a response message, and who generates that strange response. When that becomes clear, then it is time to find a way to handle it.

If such errors are handled blindly, the underlying culprit remains unknown.

**Comment by dimka59ru** [comment]
It was device with bad firmware.

**Comment by lextm** [comment]
Then, yes, you need to mark that kind of devices and handle them differently.
