### ISSUE TITLE
How to take SharpSnmpLib.Engine.dll via NuGet Manager

### ISSUE THREAD

**Issue by 2mik** [lextudio/sharpsnmplib#115]
First of all, thank you for your work.

I plan to develop SNMP agent and I need to add SharpSnmpLib.Engine.dll to my project. However I can't find this assembly in Visual Studio NuGet Manager. How to download the SharpSnmpLib.Engine.dll?

Why the SharpSnmpLib.Engine project is inside the sharpsnmplib-samples repository? It is not a sample itself.

**Comment by lextm** [comment]
https://github.com/lextudio/sharpsnmplib-samples/issues/7

It is part of two samples (`snmpd`/`snmptrapd`), and is only used for integration testing.

The quality of the code is also low, so when support policy changes it is pulled out of the core library.

**Comment by KarloX2** [comment]
Hi @lextm !

You say 

> The quality of the code is also low,

Can briefly explain or give and example for why you consider the quality low?

Thanks
