### ISSUE TITLE
Discoverer with multiple interfaces does not work

### ISSUE THREAD

**Issue by nige6** [lextudio/sharpsnmplib#117]
Discoverer with broadcast address as IPAddress,Broadcast will not broadcast to all interfaces.

so on a machine (including dev machine) with ethernet, wifi, vpns, VMs (e.g VirutalBox) will not send the broadcast on each interface
using Wireshark it's possible to see the broadcast and what interfaces/ip are being used.

Obviously using the host broadcast (e.g. 192.168.0.255) does work

**Comment by lextm** [comment]
UDP broadcast can only work under strict conditions,

1. You need to choose the right broadcast address. `snmpdiscover` sample by default uses `IPAddress.Broadcast` (in fact `255.255.255.255`) which is not likely to work in real world setup.
2. If you choose a proper broadcast IP address and produce the requests, it depends on the operating system to decide how to send them out. On Windows with multiple network adapters configured, the actual adapter to send the broadcast requests might not be the one you desired, but that's beyond the scope of this library.
3. Even when the broadcast requests arrive on the destination, it would be the receiving operating system that decides whether to process them.

Thus, without more details this discussion cannot be extended further.
