### ISSUE TITLE
Discovery problem

### ISSUE THREAD

**Issue by jonnycastaway** [lextudio/sharpsnmplib#122]
Hello et all,
i have a Problem with the discovery for snmpv3. I'm using VB.Net with Visual Studio 2015.

One of my 2 testwitches (different models)  didn't response the engineTime and engineBoots (checked with halting-point and look at the ReportMessage). The response i get is: 1.3.6.1.6.3.15.1.1.2.0 (usmStatsNotInTimeWindows) when i try GetRequestMessage. No wonder, the authentication fails without needed Data.
Test with net-snmp, Peassler SNMP Tester and SnmpB are ok. With this tools the switch is working without a problem.

The other Switch works out of the Box.

Can anyone help to find and fix the bug?

**Comment by lextm** [comment]
https://github.com/lextudio/sharpsnmplib-samples/blob/master/Samples/CSharpCore/snmpget/Program.cs#L230

**Comment by jonnycastaway** [comment]
That was the secret. Many Thanks!
I've read this about behavior before in the other issues, but thought it was implemented in the discovery. My mistake
