### ISSUE TITLE
nuget for Lextm.SharpSnmpLib.Engine no longer available?

### ISSUE THREAD

**Issue by MolallaComm** [lextudio/sharpsnmplib#123]
Lextm.SharpSnmpLib is at 11.2 and shows up in nuget
Lextm.SharpSnmpLib.Engine.Engine used to be there (i had 11.0) but no longer seems to show up at all 

perhaps this is just an intermittent problem but thought i'd mention it in case it isn't.

**Comment by lextm** [comment]
https://github.com/lextudio/sharpsnmplib-samples/issues/7
