### ISSUE TITLE
.NET Core 3.0 support

### ISSUE THREAD

**Issue by bartekkois** [lextudio/sharpsnmplib#129]
When there will be a support for .NET Core 3.0 available? Currently compiling projects with sharpsnmplib under 3.0.0 I get the following error:

  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
    - The following frameworks were found:
        3.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  
  You can resolve the problem by installing the specified framework and/or SDK.

**Comment by lextm** [comment]
Cannot reproduce this.
