### ISSUE TITLE
ParseMessages throws exception on Len - 0 return oid

### ISSUE THREAD

**Issue by rkruisECi** [lextudio/sharpsnmplib#134]
When ParseMessages throws exception on Len = 0, the OID needs to be returned with the exception thrown.

This is needed when doing a Mibwalk.  If the OID is not retunred, the Mibwalk cannot continue.

For ASN types => ObjectIdentifier, Integer32, IP, Counter32, Counter64, when a length of zero error is captured, and thrown.  We still need the oid returned.  With it not being returned, getNext requests cannot determine what is the next OID.

Example
packet =>
{ 48, 130, 0, 50, 2, 1, 0, 4, 6, 112, 117, 98, 108, 105, 99, 162, 130, 0, 35, 2, 4, 161, 113, 95, 164, 2, 1, 0, 2, 1, 0, 48, 130, 0, 19, 48, 130, 0, 15, 6, 11, 43, 6, 1, 2, 1, 25, 3, 2, 1, 4, 1, 6, 0 }

SnmpException class could have OID added, and returned, with the exception.

**Comment by lextm** [comment]
SnmpException is a generic class, so it won't contain OID.

I don't understand what you meant by "With it not being returned, getNext requests cannot determine what is the next OID", as an SNMP manager has so many ways to decide next OID to use. You have to provide a more complete scenario for further discussion.

**Comment by rkruisECi** [comment]
When ParseMessage throws an exception because of Len 0, we need to know the OID that failed, so we can use GetNext with that fail OID, to find the next OID.

**Comment by rkruisECi** [comment]
Doing a MIB walk. 
If the agent returns an invalid result halfway through, this prevents you from skipping over the invalid result and completing the walk.

**Comment by lextm** [comment]
Thanks. With that, my suggestion is that you should implement your own WALK operation, and not use the built-in methods.

Length of 0 for ObjectIdentifier, Integer32, IP, Counter32, Counter64 is an invalid scenario, which in general violates the RFC documents. I have no plan to modify #SNMP Library to accept those violations.

**Comment by cwazywabbit1974** [comment]
@lextm to clarify, I'm not asking that the exceptions be removed just that the parsed OID and requestid is returned in the exception so it's possible to move past it.  MIBs with bad data, specifically 0-length asn types and on occasion != 4 byte IP addresses, are unfortunately common. With out this it's not just the built-in WALK operation that fails, it's not possible to write one that doesn't fail (unless I'm missing something?).

When you encounter a value like this when doing a GETNEXT, you simply can't skip past it (and complete the walk) if you don't even know what OID is causing the trouble. For example, GETNEXT 1.3.6.1.4.1 could throw an error, and you need to know the OID that has the bad data in it to even be able to skip past it. If it's 1.3.6.1.4.1.12345.6.7.8 , you can't just do GETNEXT 1.3.6.1.4.1.1 GETNEXT 1.3.6.1.4.1.2 etc as they'll all fail

**Comment by lextm** [comment]
Then you are free to edit more of #SNMP Library. This is marked as won't fix like I said above. Protocol violations are not uncommon, but this project alone won't be able to cover all of them (it already covered some typical ones, but really painful to mess up the code base).
