### ISSUE TITLE
Support for SHA-224, SHA-384, SHA-512

### ISSUE THREAD

**Issue by vimesh-pro** [lextudio/sharpsnmplib#135]

**Comment by lextm** [comment]
You might implement your own authentication provider, https://github.com/lextudio/sharpsnmplib/blob/master/SharpSnmpLib/Security/IAuthenticationProvider.cs

**Comment by vimesh-pro** [comment]
Thank you 👍

**Comment by RuhanSA079** [comment]
Created a PR for SHA-384 and SHA-512.
