### ISSUE TITLE
Switch to SocketTaskExtensions

### ISSUE THREAD

**Issue by lextm** [lextudio/sharpsnmplib#136]
Microsoft introduced a new extension class with important methods to fill in the async/await gaps,

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.sockettaskextensions?view=netframework-4.8

Therefore, this library should make use of this class extensively to replace the previous hacks.

**Comment by lextm** [comment]
To use that class, the minimal .NET Framework version must be bumped to 4.7.1, and minimal .NET Standard version must be 2.0. Therefore, the library version number is bumped to 12.0.

Initial work can be found at https://www.nuget.org/packages/Lextm.SharpSnmpLib/12.0.0-alpha2/

**Comment by levant** [comment]
Seems to be fixed now in 12.0.0 which was released recently on February 18, 2020 3:02:30 PM.
My simple test case no longer crashes.
