### ISSUE TITLE
Please add timeout parameter for Messenger.GetAsync() method.

### ISSUE THREAD

**Issue by makercob** [lextudio/sharpsnmplib#140]
For unreachable target devices, the Task of Messenger.GetAsync() cannot complete, which may cause memory leaks.

**Comment by theFra985** [comment]
I think a CancellationToken parameter would be the best way to do it to keep it compilant with the Task-based async pattern but I think the problem depends from the System.Net.Sockets.Socket implementation that doesn't support it at the moment (see https://github.com/dotnet/runtime/issues/33418)

**Comment by lextm** [comment]
.NET 6 does introduce many new APIs like [this](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.sendtoasync?view=net-6.0#System_Net_Sockets_Socket_SendToAsync_System_ReadOnlyMemory_System_Byte__System_Net_Sockets_SocketFlags_System_Net_EndPoint_System_Threading_CancellationToken_), so it is now possible to better control timeout and cancelation. However, such is limited to .NET 6 runtime and impossible to port to other legacy runtimes.

**Comment by lextm** [comment]
@DubyaDude that's not really recommended. Like I commented there in the pull request, the only viable solution is to upgrade to .NET 6 which is work in progress, https://github.com/lextudio/sharpsnmplib/tree/net6

**Comment by DubyaDude** [comment]
> @DubyaDude that's not really recommended. Like I commented there in the pull request, the only viable solution is to upgrade to .NET 6 which is work in progress, https://github.com/lextudio/sharpsnmplib/tree/net6

I understand it might not be a recommended fix and my apologies I didn't see the .NET 6 branch. However, it still would've been great to add some sort of warning to the methods that have this issue for the people that are utilizing the NuGet package as this can cause some big issues for anyone who hasn't seen this.

**Comment by lextm** [comment]
@DubyaDude Developers using pre-.NET 6 based async Socket API (and all frameworks upon it) experience the same, so the issues are not limited to this specific library.

I have pinned this issue to the top of the list, but have no other plan.
