### ISSUE TITLE
Error in getting multiple variables

### ISSUE THREAD

**Issue by cpoyraz** [lextudio/sharpsnmplib#143]
Hello,
I took timeout error after calling the code below 
   var result = Messenger.Get(VersionCode.V1, new IPEndPoint(IPAddress.Parse(IpAddress), Port), new OctetString(CommunityReadOnly), variableList, 60000);

What may cause of that?

**Comment by lextm** [comment]
Check the SNMP agent log and see why. Not a surprise, as some agents don't work well when you send a very long list.
