### ISSUE TITLE
umlaut in Messenger.Get result shown as question mark

### ISSUE THREAD

**Issue by nextit** [lextudio/sharpsnmplib#144]
Hi,

all umlauts in the result (Data attribute) of Messenger.Get or Messenger.GetAync are replaced with a question mark.

**Comment by lextm** [comment]
`OctetString` is in fact not the common "string" you think of, but raw bytes. So you cannot convert them to .NET strings and expect no data lost (question marks indicate encoding issues, which is expected).

Like the test case showed, https://github.com/lextudio/sharpsnmplib/blob/master/Tests/CSharpCore/Unit/OctetStringTestFixture.cs#L90 you need to use proper encoding to decode the bytes and recover the original string.
