### ISSUE TITLE
ObjectType, ObjecyIdentity,... classes set as internal in sharpsnmplib.Mib

### ISSUE THREAD

**Issue by LouisCPro** [lextudio/sharpsnmplib#150]
After updating the package (which i did not for a long time), I see that all the classes that enable to cast IEntity to retrieve exended properties (syntas, accesslevel and so on..) are set as internal, and can not be cast to get these metadatas....

Why ?

**Comment by lextm** [comment]
`SharpSnmpLib.Mib` has been obsolete for a very long time.

**Comment by LouisCPro** [comment]
Why !

It was a really good tool to parse mibs. Do you provide another lib to replace ?

**Comment by lextm** [comment]
https://www.sharpsnmp.com/
