### ISSUE TITLE
Weird SNMP truncation error for 32-bit  (UseFullRange false not working)

### ISSUE THREAD

**Issue by SearchForTheCode** [lextudio/sharpsnmplib#154]
I have this weird "truncation error for 32-bit integer coding" when getting specific OIDs from a synology NAS. It does not happen with all synology nas systems ( even with the same firmware ), BUT also the Setting Messenger.UseFullRange = false show no effect. 

I tested and commented the error handling out and it simply worked. The snmp requests worked and i got the table data right. 
In Intege32.cs
`//if (length.Item1 > 4)
            //{
            //    throw new ArgumentException("truncation error for 32-bit integer coding", "length");
            //}`

So my question is. Will there be any side effects to this solution. What was the purpose of this if -condition anyways?
if (length.Item1 > 4)

**Comment by lextm** [comment]
Several if conditions like that were in place to test compliance against SNMP standards.

However, there are all kinds of SNMP agents that are not fully compliant, so you might need workarounds like that here and there.
