### ISSUE TITLE
Negative integer for request ID

### ISSUE THREAD

**Issue by berny275** [lextudio/sharpsnmplib#155]
This works randomly.

```
[reflection.assembly]::LoadFrom("C:\Windows\System32\Lextm.SharpSnmpLib.12.3.0\lib\netstandard2.0\SharpSnmpLib.dll")
Add-Type -Path C:\Windows\System32\Lextm.SharpSnmpLib.12.3.0\lib\netstandard2.0\SharpSnmpLib.dll

$HomeRouter = @{
    UserName   = 'snmpname'
    Target     = '4011gw'
    OID        = '1.3.6.1.2.1.1'
    AuthType   = 'SHA1'
    AuthSecret = 'authenticationpassword'
    PrivType   = 'AES128'
    PrivSecret = 'encryptionpassword'
}

$IPAddress  = [System.Net.Dns]::GetHostEntry($HomeRouter.Target).AddressList[0]
$Port = "161"
$IPEndPoint = [System.Net.IPEndPoint]::new($IPAddress, $Port)
$Timeout = "3000"
$Discovery = [Lextm.SharpSnmpLib.Messaging.Messenger]::GetNextDiscovery([Lextm.SharpSnmpLib.SnmpType]::GetRequestPdu)
$report = $Discovery.GetResponse($Timeout, $IPEndPoint)

```

Sometimes this works, sometimes it doesn't.

Whenever it doesn't work, when I look at the request-id in the packets, the request ID is a negative integer.
Whenever it does work, the request-id is a positive integer.

**Comment by lextm** [comment]
https://github.com/lextudio/sharpsnmplib/blob/12.3.0/SharpSnmpLib/Messaging/Messenger.cs#L65

Read the comments and you know how to move on.

**Comment by berny275** [comment]
For those playing along in powershell space...

[Lextm.SharpSnmpLib.Messaging.Messenger]::UseFullRange = $false

If you're using the snmpv3 module, then you'll need to do this:

Import-Module snmpv3
[Lextm.SharpSnmpLib.Messaging.Messenger]::UseFullRange = $false

You need to do the declaration before doing anything like Invoke-SNMPv3Walk which would start the discovery process and start [Lextm.SharpSnmpLib.Messaging.Messenger]::GetNextDiscovery
