### ISSUE TITLE
Messenger.Walk timeout is not applied to call

### ISSUE THREAD

**Issue by mjanulaitis** [lextudio/sharpsnmplib#156]
When calling Messenger.Walk the timeout is applied to each HasNext call which although appropriate is not applied to the loop around the HasNext call.  The time should be applied to both each HasNext call and the entire loop.

**Comment by lextm** [comment]
By design. You can wrap up the call with your own timer, which triggers the necessary timeout you want.

**Comment by mjanulaitis** [comment]
Yes I did this already:

         try
                {
                    var receiver = new IPEndPoint(ip, model.Port);
                    var vList = new List<Variable>();

                    var task = Messenger.WalkAsync(ToVersionCode(model.Version), receiver, new OctetString(model.CommunityGet), objectIdentifier, vList, WalkMode.WithinSubtree);
                    if (!task.Wait(model.TimeoutTicks, cancellationToken))
                        throw new System.TimeoutException();

                    return vList;
                }
                catch (System.TimeoutException)
                {
                    throw;
                }

**Comment by mjanulaitis** [comment]
That's all find and dandy but the task will continue to run.  In my case I am walking a Windows machine which takes so long I have never seen it complete.  The running task that consumes the CPU.
