### ISSUE TITLE
Make use of .NET 6 new socket API such as cancelation token support

### ISSUE THREAD

**Issue by lextm** [lextudio/sharpsnmplib#160]
.NET 6 finally introduces new socket API such as `Socket.SendToAsync` with cancelation token support,

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.sendtoasync?view=net-6.0#System_Net_Sockets_Socket_SendToAsync_System_ReadOnlyMemory_System_Byte__System_Net_Sockets_SocketFlags_System_Net_EndPoint_System_Threading_CancellationToken_

#SNMP Library can added new methods to adapt to such changes.

#140 is only one of the scenarios.

**Comment by zivillian** [comment]
I've create a first draft of an implementation which should work on all supported platforms.

https://github.com/zivillian/sharpsnmplib/commit/6c71154744f7411c5037e61ffc64602fbe621c9d

The [SocketExtension implementation ](https://github.com/zivillian/sharpsnmplib/commit/6c71154744f7411c5037e61ffc64602fbe621c9d#diff-a1f626502c831fc94dafa76ccaab12fb8fef5818d6851efe13b2e47b1cecc6abR35-R38) can later be made platform dependent to use the native implementation for net6.

What do you think? Should I complete the implementation and add remaining overloads and CancellationToken parameter?

**Comment by lextm** [comment]
@zivillian It looks nice, and I start to wonder if we should ship the newly implemented methods in a separate library (NuGet package). The benefit of a separate package is that we can explicitly mark it as .NET 6 and above only (instead of adding conditional compilation in the current library).

**Comment by lextm** [comment]
Is being worked in https://github.com/lextudio/sharpsnmplib/tree/net6

**Comment by lextm** [comment]
Implemented in recent commits.
