### ISSUE TITLE
wrong response sequence: expected -594452, received 16182764

### ISSUE THREAD

**Issue by bo100nka** [lextudio/sharpsnmplib#168]
Hello!

i am using the `Lextm.SharpSnmpLib 12.4.0` nuget in a .net core 3.1 program and am querying a single OID of an SNMP agent with Version1 client and i get this error:
`wrong response sequence: expected -594452, received 16182764.`

When i try this using some other tool (iReasoning's MIB Browser) then it succeeds but not with my client that uses this nuget.

When I query some other devices (different IP address) then i get a success response for both my client and the mib browser tool.

The device is in a customer's server for which i do not have access, so i only send them my client app which they execute and only send me a log file back.

How can i "Debug" or view why is this happening? Any diagnostic questions/info i should ask the customer to investigation about the device?

Thank you for help in advance

**Comment by lextm** [comment]
You might get started from https://docs.sharpsnmp.com/tutorials/troubleshooting.html

**Comment by bo100nka** [comment]
few days later they just restarted the service and it started to work... when they try to restart it on the day of deployment it didn't help so perhaps this was an environment issue at their side
