### ISSUE TITLE
Rijndael is used for AES on 4.7

### ISSUE THREAD

**Issue by mjanulaitis** [lextudio/sharpsnmplib#171]
The call to use Rijndael for AES busts FIPS compliance.

**Comment by mjanulaitis** [comment]
I have modified the Encrypt function in a branch of my own and it appears to be working, at least when I fire AES traps from a .Net Framework app using your library. I have a real test with a top defense contractor tomorrow so we will see.  I removed all the .NET 6 and 5 code because, my experience with the worlds top employer and the defense contractors that support them, run on Windows with a little Linux sprinkled undeath, not phones.  No need to support core.  Here it is...notice the feedback size is remarked.

```
public byte[] Encrypt(byte[] key, byte[] iv, byte[] unencryptedData)
{
    using (var rm = Aes.Create())
    {
        rm.KeySize = KeyBytes * 8;
        //rm.FeedbackSize = 128;
        rm.BlockSize = 128;

        // we have to use Zeros padding otherwise we get encrypt buffer size exception
        rm.Padding = PaddingMode.Zeros;
        rm.Mode = CipherMode.CFB;

        rm.Key = key;
        rm.IV = iv;
        using (var cryptor = rm.CreateEncryptor())
        {
            var encryptedData = cryptor.TransformFinalBlock(unencryptedData, 0, unencryptedData.Length);

            // check if encrypted data is the same length as source data
            if (encryptedData.Length != unencryptedData.Length)
            {
                // cut out the padding
                var tmp = new byte[unencryptedData.Length];
                Buffer.BlockCopy(encryptedData, 0, tmp, 0, unencryptedData.Length);
                return tmp;
            }

            return encryptedData;
        }
    }
}

public byte[] Decrypt(byte[] key, byte[] iv, byte[] encryptedData)
{
    // now do CFB decryption of the encrypted data
    using (var rm = Aes.Create())
    {
        rm.KeySize = KeyBytes * 8;
        //rm.FeedbackSize = 128;
        rm.BlockSize = 128;
        rm.Padding = PaddingMode.Zeros;
        rm.Mode = CipherMode.CFB;

        rm.Key = key;
        rm.IV = iv;
        using (var cryptor = rm.CreateDecryptor())
        {
            // We need to make sure that cryptedData is a collection of 128 byte blocks
            byte[] decryptedData;
            if ((encryptedData.Length % MinimalBlockSize) != 0)
            {
                var div = encryptedData.Length / MinimalBlockSize;
                var newLength = (div + 1) * MinimalBlockSize;
                var decryptBuffer = new byte[newLength];
                Buffer.BlockCopy(encryptedData, 0, decryptBuffer, 0, encryptedData.Length);
                decryptedData = cryptor.TransformFinalBlock(decryptBuffer, 0, decryptBuffer.Length);

                // now remove padding
                var buffer = new byte[encryptedData.Length];
                Buffer.BlockCopy(decryptedData, 0, buffer, 0, encryptedData.Length);
                return buffer;
            }

            decryptedData = cryptor.TransformFinalBlock(encryptedData, 0, encryptedData.Length);
            return decryptedData;
        }
    }
}
```

**Comment by lextm** [comment]
No. Your modification is invalid, as SNMP v3 explicitly asks for feedback size of 128, https://datatracker.ietf.org/doc/html/rfc3826#page-8

> **The data is encrypted in Cipher Feedback mode with the parameter s
   set to 128** according to the definition of CFB mode given in [Section](https://datatracker.ietf.org/doc/html/rfc3826#section-6.3)
   [6.3](https://datatracker.ietf.org/doc/html/rfc3826#section-6.3) of [[AES-MODE](https://datatracker.ietf.org/doc/html/rfc3826#ref-AES-MODE)].

**Comment by lextm** [comment]
Bouncy Castle has a different API surface for its FIPS version, so if you insist you can port `BouncyCastleAESPrivacyProvider` and its siblings over to support that special library. However, those classes are considered part of the unsupported sample repo.

Like I commented earlier, FIPS compliance was never a goal of this project, so any user wanting that (only a small portion) needs to help himself/herself. There is no need to bother most users with any extra dependency when they don't need/request that.

**Comment by mjanulaitis** [comment]
Ok that's interesting...you say a different API for FIPS.  So are you saying the Portable.BouncyCastle is not FIPS compliant?
