### ISSUE TITLE
No error on invalid user name (V3 get request)

### ISSUE THREAD

**Issue by Alquas** [lextudio/sharpsnmplib#172]
Hello!

I faced a strange situation and wanted to know if it was intended behavior from the devs (as it has both pros (I guess) and cons).

Using the code below returns the intended values when providing the correct credentials,
However altering the user name outputs the OID corresponding to the number of connections with invalid username.

```cs
var ip = IPAddress.Parse("[redacted]");

string userName = "[redacted]";
string authPass = "[redacted]";
string privPass = "[redacted]";


Discovery discovery = Messenger.GetNextDiscovery(SnmpType.GetRequestPdu);
ReportMessage report = discovery.GetResponse(5000, new IPEndPoint(ip, 161));

var auth = new MD5AuthenticationProvider(new OctetString(authPass));
var priv = new DESPrivacyProvider(new OctetString(privPass), auth);

GetRequestMessage request = new GetRequestMessage(VersionCode.V3, Messenger.NextMessageId, Messenger.NextRequestId, new OctetString(userName), new List<Variable>{new Variable(new ObjectIdentifier("1.3.6.1.2.1.1.1.0"))}, priv, Messenger.MaxMessageSize, report);
ISnmpMessage reply = request.GetResponse(60000, new IPEndPoint(ip, 161));
if (reply.Pdu().ErrorStatus.ToInt32() != 0) // != ErrorCode.NoError
{
	throw ErrorException.Create(
		"error in response",
		ip,
		reply);
}

var pdu = reply.Pdu();
var result = pdu.Variables;

foreach (var r in result) {
	Console.WriteLine(r);
}
```

**output with valid username** (and passwords)**:**

`Variable: Id: 1.3.6.1.2.1.1.1.0; Data: [redacted]`
which is the expected behavior

**output using invalid username:**

`Variable: Id: 1.3.6.1.6.3.15.1.1.3.0; Data: 3`
which is the OID correponding to
> The total number of packets received by the SNMP
> engine which were dropped because they referenced a
> user that was not known to the SNMP engine.

where I would have expected an error to occur (much like with the snmp cli tool)

**Comment by lextm** [comment]
SNMP v3 errors are not all captured in `ErrorStatus`, so it will be your responsibility to add checks on the response message type (RESPONSE or REPORT) to verify whether an error occurs. The samples are just there to get you started, not enough to handle real world situations.

**Comment by Alquas** [comment]
Ok thanks.
Nice library by the way.
