### ISSUE TITLE
Invalid message bytes found. Use tracing to analyze the bytes.: unsupported data type: 189

### ISSUE THREAD

**Issue by hy-net** [lextudio/sharpsnmplib#175]
Not sure what is the root cause, but if it is simply because of data type, can we just assume anything that we can't interpreted as byte array or string?

0000:   30 82 01 D4 02 01 03 30 11 02 04 01 AE BA EB 02    0.Ô...0....®ºë.
0010:   03 00 FF E3 04 01 07 02 01 03 04 39 30 37 04 0D    ..ÿã.......907..
0020:   80 00 1F 88 80 B7 72 B7 4A 16 FF 44 58 02 01 52    ..·r·J.ÿDX..R
0030:   02 03 01 DC 19 04 06 61 76 61 79 61 79 04 0C A4    ...Ü...avayay..¤
0040:   47 8D D6 34 02 03 18 C8 E7 45 EC 04 08 D7 A1 86    GÖ4...ÈçEì..×¡
0050:   54 2E 22 37 AD 04 82 01 7F AB 89 01 0B 0B 41 7F    T."7­..«...A
0060:   BC A1 C6 33 59 77 C5 82 E5 79 AD 94 45 53 56 FA    ¼¡Æ3YwÅåy­ESVú
0070:   AB E5 D6 A4 69 35 84 1C 50 82 B8 9B DF 06 FF 1F    «åÖ¤i5.P¸ß.ÿ.
0080:   21 74 9C F8 C1 B7 1F 4F 77 F3 1D 4E EF 71 32 F6    !tøÁ·.Owó.Nïq2ö
0090:   C8 4F 97 D9 5A 66 43 27 98 35 D9 79 70 9E 6A F1    ÈOÙZfC'5Ùypjñ
00A0:   C1 C4 4B 67 E0 31 C9 57 5E 19 24 D9 55 F7 5D B1    ÁÄKgà1ÉW^.$ÙU÷]±
00B0:   50 C9 87 93 6B D0 58 0D 67 D6 F4 66 71 8C 3C 43    PÉkÐX.gÖôfq<C
00C0:   11 14 37 DB DF 61 E2 2D BF 27 94 F8 43 07 6A 0F    ..7Ûßaâ-¿'øC.j.
00D0:   BC C8 76 09 91 11 B4 02 58 09 54 58 FE 60 5D 08    ¼Èv..´.X.TXþ`].
00E0:   CA 90 16 18 83 AE 05 A2 E9 A8 16 B1 A1 60 40 44    Ê..®.¢é¨.±¡`@D
00F0:   31 FD 48 3C C5 30 2E DF 06 73 C2 B9 3D 81 19 01    1ýH<Å0.ß.sÂ¹=..
0100:   15 D6 86 01 9F 11 4F CC CB 98 61 B5 9B 5C 0E B3    .Ö..OÌËaµ\\.³
0110:   A3 89 BB B3 01 D6 C5 01 98 F2 D8 80 32 11 AB A8    £»³.ÖÅ.òØ2.«¨
0120:   0B 76 5B 82 02 93 76 F8 14 06 90 0B C5 44 B8 7E    .v[.vø...ÅD¸~
0130:   83 38 28 19 A2 E1 29 8D 5D B4 65 78 73 63 9A CC    8(.¢á)]´exscÌ
0140:   53 A2 E5 60 9D 56 9C F9 02 2B BF 5D 82 AF 37 EA    S¢å`Vù.+¿]¯7ê
0150:   31 C9 CB 9F 92 64 9F 56 50 ED E1 A0 59 F2 66 20    1ÉËdVPíá Yòf 
0160:   80 05 FB DB 15 17 A4 A3 4A 7A B8 0F 72 97 E1 71    .ûÛ..¤£Jz¸.ráq
0170:   6A 56 7B 47 76 DA 52 9E 98 FD 3E 66 C6 99 2D 74    jV{GvÚRý>fÆ-t
0180:   87 03 C9 AC 4E B0 AD F9 EF 08 82 2A 74 A7 76 33    .É¬N°­ùï.*t§v3
0190:   89 0D D7 05 27 D0 68 67 EF 66 8C 79 23 E2 E1 55    .×.'Ðhgïfy#âáU
01A0:   BF 80 03 2C F0 5E CB FA 4A CC 9A 14 20 EF 88 BD    ¿.,ð^ËúJÌ. ï½
01B0:   1C 9B 39 13 52 34 26 9D 37 CE B7 84 75 46 7A 58    .9.R4&7Î·uFzX
01C0:   2D 22 67 5F 46 C3 60 9A 43 B8 C4 CD F9 E9 BD 5B    -"g_FÃ`C¸ÄÍùé½[
01D0:   E9 59 A6 BB 65 A3 5E 9E 00 00 00 00 00 00 00 00    éY¦»e£^........
01E0:   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
01F0:   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................

.... the rest are just 00000

**Comment by lextm** [comment]
You probably can get some hints from #89.

"if it is simply because of data type, can we just assume anything that we can't interpreted as byte array or string". No, we cannot. There is chain reactions behind, so throwing exceptions and terminating early can save endless efforts.
