### ISSUE TITLE
Is it right [Obsolete] attribute are set in different overloads  between GetRequestMessage and SetRequestMessage ?

### ISSUE THREAD

**Issue by MORI-HAMAMATSU** [lextudio/sharpsnmplib#179]
Obsolete attribute of GetRequestMessage and SetRequestMessage constructor are set in different overloads currently as below.

-  GetRequestMessage constructor

    GetRequestMessage(int, VersionCode, OctetString, IList< Variable >)
    **GetRequestMessage(VersionCode, int, int, OctetString, IList< Variable >, IPrivacyProvider, ISnmpMessage) ... OBSOLETE**
    GetRequestMessage(VersionCode, int, int, OctetString, IList< Variable >, IPrivacyProvider, int, ISnmpMessage)
    GetRequestMessage(VersionCode, int, int, OctetString, OctetString, IList< Variable >, IPrivacyProvider, int, ISnmpMessage)

-  SetRequestMessage constructor

    SetRequestMessage(int, VersionCode, OctetString, IList< Variable >)
    SetRequestMessage(VersionCode, int, int, OctetString, IList< Variable >, IPrivacyProvider, ISnmpMessage)
    **SetRequestMessage(VersionCode, int, int, OctetString, IList< Variable >, IPrivacyProvider, int, ISnmpMessage) ... OBSOLETE**
    SetRequestMessage(VersionCode, int, int, OctetString, OctetString, IList< Variable >, IPrivacyProvider, int, ISnmpMessage)

I think maybe obsolete attribute of SetRequestMessage constructor is set in wrong overload.
(Maybe SetRequestMessage(VersionCode, int, int, OctetString, IList< Variable >, IPrivacyProvider, ISnmpMessage) should be set obsolete)

These changes were done in [Removed obsolete attributes.](https://github.com/lextudio/sharpsnmplib/commit/0938ff1205bf705d90d7d8e056f002fadf0e8b7f)

![image](https://user-images.githubusercontent.com/6880353/196399349-19f194d4-17e5-453f-8953-a912a7358b5d.png)

Is there are any historical reason of this?
Or obsolete attribute of SetRequestMessage constructor is set in wrong overload ?

Your confirmation would be appreciated.

**Comment by lextm** [comment]
Actually more obsolete notes should be added. Fixed in cbe8cdcf3140bcff5e722fbfe0baa3b11046f0b6
