### ISSUE TITLE
Error serializing custom Exceptinon classes with DataContract attribute

### ISSUE THREAD

**Issue by michalsgit** [lextudio/sharpsnmplib#181]
Exceptions SnmpException, ErrorException, AccessFailureException, MessageFactoryException, PortInUseException, TimeoutException, OperationException and DecryptionException have DataContract but also implements ISerializable via Exception.

This lead to serialization exceptions like: 
Type 'Lextm.SharpSnmpLib.Messaging.ErrorException' cannot be ISerializable and have DataContractAttribute attribute.

Is there any reason to have DataContract on the exceptions?

**Comment by lextm** [comment]
Fixed in 12.5.2.
