### ISSUE TITLE
SNMPv3 - Handle authentication errors

### ISSUE THREAD

**Issue by BornToBeRoot** [lextudio/sharpsnmplib#184]
Hi @lextm,

first of all great library and I already found this issue (https://github.com/lextudio/sharpsnmplib/issues/172) about it.

I think it makes sense that the library handles some SNMP v3 errors like `Unkown username` or `Authentication failure`. Similar to tools like snmpget/walk:

![image](https://user-images.githubusercontent.com/16019165/233871527-f5d81e35-cdca-426e-921e-e1c46fa812bc.png)

Otherwise every tool using this lib has to implement this basic validation itself.

What I also noticed... when I do a GET, it returns the OID with the error. With a WALK simply nothing comes back. Neither a general error nor an OID with the error. Any idea how to check for an error in a WALK? (Maybe my implementation is wrong: https://github.com/BornToBeRoot/NETworkManager/blob/f5dd63689399d4d0b43802478a35e2020c516bac/Source/NETworkManager.Models/Network/SNMPClient.cs#L177)

I have seen that you have a function GetErrorMessage and here already some errors should be caught. Is this implemented in all methods?

Thanks and greetings
BornToBeRoot

**Comment by lextm** [comment]
It is recommended that you implement your own `BulkWalkAsync` method to achieve that, which isn't very hard.

There is currently no plan to improve anything under `Messenger`.

**Comment by BornToBeRoot** [comment]
For anyone looking for a solution. Here is mine: https://github.com/BornToBeRoot/NETworkManager/blob/5396a62aed8114f0663e7850fd3b8b9c825720bf/Source/NETworkManager.Models/Network/SNMPClient.cs
