### ISSUE TITLE
Casting ISnmpPdu.Variable.Data to Int for a SetRequestMessage

### ISSUE THREAD

**Issue by Brehtyn** [lextudio/sharpsnmplib#194]
Some variable-bindings expect their data types to be int instead of string. Currently it seems like its only possible to use ISnmpPdu.Variables.Data with StringOctet type, Trying to make a SetPDU request using this variable results in the SNMP error 7 - (wrongType) if a type of int is expected.

Am I missing the way to send ISnmpPdu.Variables.Data as an int using Lexm.SharpSNMP without modifying the library?

**Comment by lextm** [comment]
What's the Net-SNMP command line you use to perform this SET operation? If you can provide that, then not difficult to find the equivalent C# code.

**Comment by Brehtyn** [comment]
"snmpset -v=3 -l=authPriv -a=SHA -A=REDACTED -x=DES -X=REDACTED -u=localadmin localhost 1.3.6.1.4.1.850.1.1.3.2.3.3.1.1.6.7.6 i 1" does the trick.

Looking at that sample it looks like it's just initialize a ISnmpData variable and then set it equal to a new instance of whatever type we need. 

something like 
`
ISnmpData data;
data = new Integar(variable) 
`

does the trick. 

Thanks! I was looking at your docs for how to do this and didn't think to look back at the examples. If I have time, could I flesh them out as a thank you for putting together this library and answering questions?

**Comment by Brehtyn** [comment]
"snmpset -v=3 -l=authPriv -a=SHA -A=REDACTED -x=DES -X=REDACTED -u=localadmin localhost 1.3.6.1.4.1.850.1.1.3.2.3.3.1.1.6.7.6 i 1" for the command line sample.

Looking at that sample's source, it looks like it's just initialize a ISnmpData variable and then set it equal to a new instance of whatever type we need.

something like
ISnmpData data; 
data = new Integer32(variable);

does the trick. Simple!

Thank you! I was looking at your docs for how to do this and didn't think to look back at the examples. If I have time, could I flesh them out as a thank you for putting together this library and answering questions?
