### ISSUE TITLE
Walk() has incorrect behaviour for SNMP v2

### ISSUE THREAD

**Issue by luke-waymark-addinsight** [lextudio/sharpsnmplib#195]
According to `RFC 1905 Protocol Operations for SNMPv2` in `4.2.2` the `GetNextRequest-PDU` works the same as the `GetBulkRequest-PDU` when there's no more successors - set the name to the requested OID and value with `endOfMibView`.

`BulkWalk()` correctly checks for this while iterating but the normal `Walk()` does not, despite the docstring stating V2 support.

This is a simple fix to copy the same `endOfMibView` check over to the three walk functions before it calls `HasNext()` (optionally guarded for V2).

I've added this check myself and tested using `pysnmp`'s `snmpsim` which does indeed set the value to `endOfMibView` in a `GetNextRequest` for a v2 request. Without this fix calling `Walk()` causes an infinite loop as the `seed` value never changes since the return OID is the same as the request, and it won't timeout either.
(A V1 next request works fine as `snpmsim` uses `error = noSuchName` as expected)

**Comment by lextm** [comment]
Currently no plan to fix this. You can implement your own `Walk` method instead.

**Comment by lextm** [comment]
Thanks for the pull request. Shipped in release 12.5.5.
