### ISSUE TITLE
The SocketAwaitable class seems to be leaking resources.

### ISSUE THREAD

**Issue by MareMare** [lextudio/sharpsnmplib#24]
The SocketAwaitable class seems to be leaking resources in #SNMP v 9.0.3.
I think it is probably caused by strong reference.

```cs
public SocketAwaitable(SocketAsyncEventArgs eventArgs)
{
    if (eventArgs == null)
    {
        throw new ArgumentNullException(nameof(eventArgs));
    }

    this.m_eventArgs = eventArgs;
    eventArgs.Completed += delegate   // <----- strong reference?
    {
        var prev = m_continuation ?? Interlocked.CompareExchange(
            ref m_continuation, SENTINEL, null);
        if (prev != null) prev();
    };
}
```

It might be better to do the following:
```cs
public SocketAwaitable(SocketAsyncEventArgs eventArgs)
{
    if (eventArgs == null)
    {
        throw new ArgumentNullException(nameof(eventArgs));
    }

    this.m_eventArgs = eventArgs;

    // Instead of anonymous method, change to private method...
    eventArgs.Completed += this.eventArgs_Completed;
}
private void eventArgs_Completed(object sender, SocketAsyncEventArgs e)
{
    var prev = m_continuation ?? Interlocked.CompareExchange(
        ref m_continuation, SENTINEL, null);
    if (prev != null) prev();
}
internal void Reset()
{
    // Release event handler at reset...
    this.m_eventArgs.Completed -= this.eventArgs_Completed;
    this.m_wasCompleted = false;
    this.m_continuation = null;
}
```

How is it?

**Comment by lextm** [comment]
First, I don't think that causes a memory leak. I have previously used dotMemory to prove, https://blog.lextudio.com/2015/06/analysis-on-a-snmp-library-memory-leak-report-with-jetbrains-dotmemory/ If you do observer leak via a profiler, please provide more details.

Seconds, after compilation the compiler already creates an instance method (like your handwritten private method), so your change is unnecessary.  You might refer to https://blogs.msdn.microsoft.com/oldnewthing/20060802-00/?p=30263

**Comment by MareMare** [comment]
Thanks for quick reply. 

> If you do observer leak via a profiler, please provide more details.

I prepared details that seems to be memory leak.
I ran it in the situation where the following timeout occurs:

* The SNMP agent exists on host B, but it is not running.
* Running [my test code](https://gist.githubusercontent.com/MareMare/1d0876da3f50abdeb0f5720a512962a2/raw/fbe339441710002bd58b92979370dd8ca04b7249/GetAsyncWithCancellation.cs) (Console App) on host A.

My test code snippet is below:

```cs
var response = await message.GetResponseAsync(new IPEndPoint(IPAddress.Parse("IP OF HOST B"), 161))
    .WithCancellation(cts.Token)
    .ConfigureAwait(false);
```

The snapshot with dotMemory is below:

1. Compare snapshots
![image1](https://gist.githubusercontent.com/MareMare/1d0876da3f50abdeb0f5720a512962a2/raw/fbe339441710002bd58b92979370dd8ca04b7249/dotMemoryCompareSnapshots.png)

2. Object Set(SocketAwaitable)
![image2](https://gist.githubusercontent.com/MareMare/1d0876da3f50abdeb0f5720a512962a2/raw/fbe339441710002bd58b92979370dd8ca04b7249/dotMemoryObjectSet-SocketAwaitable.png)


I think it is leaking with SocketAwaitable, is it wrong?

**Comment by lextm** [comment]
`SocketAwaitable` has its life span as local variable in all allocations. Thus, it should be freed automatically (though it can be slow).

I just made an experimental commit c8cba7e2513f3bc839441f59fabb9da5740c7401 which changes both how `SocketAsyncEventArgs` and `SocketAwaitable` are handled. You can test that out, and should observe significant less objects in the heap.

**Comment by MareMare** [comment]
I tried c8cba7e. It certainly seems that there is no problem if the SNMP Agent on the remote host responds.

However, if the SNMP Agent on the remote host does not respond (e.g. snmpd.exe is not listening), it **still leaks**.

Apparently, if `CancellationTokenSource` caused an` OperationCanceledException` exception, it seems that the socket in the `GetResponseAsync(this ISnmpMessage, IPEndPoint)` method has not been disposed.

Perhaps it may be necessary to overload the `GetResponseAsync` method to receive `CancellationToken`.

e.g.
`public static async Task<ISnmpMessage> GetResponseAsync(this ISnmpMessage, IPEndPoint, CancellationToken)`

**Comment by lextm** [comment]
I don't see an easy fix yet. Probably it can only be resolved after more investigation.

**Comment by MareMare** [comment]
With a slightly different approach, I tried the following:
```cs
                using (var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(this.cts.Token, cancellationToken))
                using (var client = UdpClientWrapper.CreateClient())
                {
                    var sendingBytes = request.ToBytes();
                    var sendingTask = client.SendAsync(sendingBytes, sendingBytes.Length, remoteEndPoint);
                    var sentBytesSize = await sendingTask.WithCancellation(linkedCts.Token).ConfigureAwait(false);

                    var receivingTask = client.ReceiveAsync();
                    var receiveResult = await receivingTask.WithCancellation(linkedCts.Token).ConfigureAwait(false);

                    var reply = receiveResult.Buffer;
                    var registry = new UserRegistry();
                    var response = MessageFactory.ParseMessages(reply, 0, receiveResult.Buffer.Length, registry)[0];

                    var responseCode = response.TypeCode();
                    if (responseCode == SnmpType.ResponsePdu || responseCode == SnmpType.ReportPdu)
                    {
                        var requestId = request.MessageId();
                        var responseId = response.MessageId();
                        if (responseId != requestId)
                        {
                            throw OperationException.Create(string.Format(CultureInfo.InvariantCulture, "wrong response sequence: expected {0}, received {1}", requestId, responseId), remoteEndPoint.Address);
                        }

                        return response;
                    }

                    throw OperationException.Create(string.Format(CultureInfo.InvariantCulture, "wrong response type: {0}", responseCode), remoteEndPoint.Address);
                }
```

The complete code is below:
[my tried code](https://gist.github.com/MareMare/a56fc3f4bba183317764494f3af990c7#file-getasyncwithcancellation2-cs)

The amount of change may be large, but is it likely to be useful?

**Comment by mibsi** [comment]
I found the same issue.
Do you plan any fix?

**Comment by isurakka** [comment]
This is a problem in my use case also. If the SNMP target is down for a long time this leaks memory until you start getting out of memory exceptions.

**Comment by kmiller77** [comment]
I would love a fix for this as well, but for now I am going to try the solution from @MareMare

**Comment by kmiller77** [comment]
I have been using the fix from @MareMare for a while now, but I am (very) occasionally getting Out Of Memory Exceptions. I'm not 100% sure that this exact fix has been the problem (still trying to gather more information). I was kind of wondering if anyone else with the same solution has had issues as well as if this is still in the plans to be resolved?

**Comment by lextm** [comment]
#136 should remedy the issue at last. Please test and provide feedback there.
