### ISSUE TITLE
getting Traps from MIB using mib browser

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#345]
we are using honeycell_6.1.1 version.

is it possible to get the Traps or NOTIFICATION related information from Mib
file.

for eaxample i have a MIB file which has traps listed in that. will Mib
Browser supports to get the all the list of traps and trap related inforamtion
(like Variable bindings list, description etc) from that mib?

i have complied my mib file and loaded compled modules in mib browser.

i could not see any traps or NOTIFICATION relaed in Items in Mib Tree? will
MIB Browser supports this?

Regards,

DG

**Original Reported Date**: 2011-08-24T11:48:13.427-07:00
**Original CodePlex Discussion Thread ID**: 270259

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

The current MIB compiler cannot achieve this.

Regards,

Lex



**Original Posted Date**: 2011-08-26T04:59:38.713-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi Lex

Thanks for the relpy

We would like to know, Are there any plans for this functionality support?

Regards,

DG



**Original Posted Date**: 2011-08-29T21:15:49.847-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

A better compiler has been in the TODO list for several years, but it is not
an easy goal to achieve.

Currently I am trying to port Mibble MIB Parser from Java to C# and hope to
finish that for #SNMP 8.0. Note that it is GPLed.

Regards,

Lex



**Original Posted Date**: 2011-08-30T03:41:37.773-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T04:24:11.877-07:00

**Comment by lextm** [comment]
Later implemented in [#SNMP Pro](https://pro.sharpsnmp.com].
