### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#364]
I've looked through the sample files but they seem to be just the code for
building the command line tools. Is there any documentation for creating a
simple SNMP get command similar to other snmp libraries like
http://www.codeproject.com/Articles/12993/SNMP-library.

  
I am running into a problem also when using the command line utility
snmpwalk.exe which returns strange output:

C:\SNMP>snmpbulkget -c=public@1 192.168.1.1 1.3.6.1.2.1.17.4.3.1.1  
Variable: Id: .1.3.6.1.2.1.17.4.3.1.1.0.0.72.201.72.143; Data:   H?H?  
Variable: Id: .1.3.6.1.2.1.17.4.3.1.1.0.0.116.224.28.132; Data:   t?∟?  
Variable: Id: .1.3.6.1.2.1.17.4.3.1.1.0.0.116.229.252.122; Data:   t??z  
Variable: Id: .1.3.6.1.2.1.17.4.3.1.1.0.0.116.247.157.192; Data:   t???  
Variable: Id: .1.3.6.1.2.1.17.4.3.1.1.0.0.170.100.135.207; Data:   ?d??

**Original Reported Date**: 2012-04-18T09:05:19.273-07:00
**Original CodePlex Discussion Thread ID**: 352709

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Well, the command line tools are so small (only a few lines), so personally I
don't see a need to provide even smaller samples.

You may refer to older discussion threads instead,

<http://sharpsnmplib.codeplex.com/discussions/255472>

For mangled characters you saw, they were generated by converting bytes to
ASCII strings,

<http://www.lextm.com/2008/09/snmp-design-breaking-changes-coming.html>

If the original bytes contain Unicode strings (or any other encoding),
converting to ASCII will lead to such output. In your code you should use
proper encoding to decode the bytes, while as a general purpose sample,
snmpbulkget (or other samples) always use ASCII for simplicity.

Regards,

Lex



**Original Posted Date**: 2012-04-18T19:58:25.363-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T04:14:48.23-07:00

**Comment by lextm** [comment]
Similar to #412, proper decoding of complex date types requires MIB documents and SMI compilation. Those features are only available in #SNMP Pro.
