### ISSUE TITLE
MIB Compiler - Object Type Syntax

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#406]
Hi,

I am looking to make use of the MIB compiler for more than just OID
translations.  As I understand it, the compiler does not currently support
compiling the syntax of object types.  Is there any work currently going on to
make this possible?  Is it worth me starting something like this myself -
would you be receptive to integrating this with the current compiler?

In order to make an application dynamic, in the sense that it gets it
information from a loaded MIB, we really need syntax resolution against an OID
in order to make a set request, else we risk sending the wrong type.  I see
this as a big feature which could add a lot to #SNMP.

It would be good to hear your thoughts on this.

Thanks.

**Original Reported Date**: 2011-06-02T06:22:10.433-07:00
**Original CodePlex Discussion Thread ID**: 259928

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi,

You have two choices,

  1. Nemo157 enhanced the compiler underlying code a lot for 7.0 release (but he met some problems still), but I did not yet have time to make use of the enhancement in Compiler.exe. You can create a fork to dig in that area.
  2. Or alternatively you can create a new compiler (based on ANTLR or another compiler generator tool).

That's all I can think of at this moment.

Due to some health problem, recently I have little time to work on this
project.

Regards,

Lex



**Original Posted Date**: 2011-06-05T21:51:12.81-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Sorry to hear that, I will keep you updated as to the progress.

Thanks.



**Original Posted Date**: 2011-06-09T01:53:20.92-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T04:43:07.143-07:00

**Comment by lextm** [comment]
Type resolution was only introduced in #SNMP Pro. More information can be found at https://pro.sharpsnmp.com
