### ISSUE TITLE
OctetString ToString and ToHexString 

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#412]
I am having problems walking a tree and determining the appropriate data
types.  
  
Consider the following OIDS:  
sysName= .1.3.6.1.2.1.1.5.0  
hrPrinterDetectedErrorState = 1.3.6.1.2.1.25.3.5.1.2.1  
  
If I use snmpwalk.exe, I see sysname is of type "STRING" and
hrPrinterDetectedErrorState is of type "Hex-STRING". When I try to emulate
this in code, I see both of these values are TypeCode = 4 which is
Octetstring.  
  
If I try to convert all octet variables with the ToString Method then
hrPrinterDetectedErrorState will contain a garbage string and not a number.
However, if I use ToHexString method, then sysName is converted to hex not the
pretty string that I would like to see.  
  
How can I problematically determine when to use ToString and when to use
toHexString?

**Original Reported Date**: 2009-04-29T08:28:29.877-07:00
**Original CodePlex Discussion Thread ID**: 54844

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi,

  

First, SNMP does not have a basic type like Hex-STRING. Hex-STRING is a custom
data type that is based on OCTET STRING. That's why you noticed that TypeCode
= 4.

  

Second, snmpwalk in Net-SNMP actually parses MIB documents before printing out
its output, so it has a chance to know which object is basic OCTET STRING, and
which is Hex-STRING. That's a trick behind the scene.

  

Third, at this moment, #SNMP MIB Compiler is not able to extract Hex-STRING
and so on from MIB documents, so the behavior you met is well, by design.
Unless our new compiler ships, it is not easy to determine when to use
ToString and when to use ToHexString.

  

Fourth, generally speaking, to manage a known device WALK operation is not
used as frequently as GET, SET, GET-NEXT and so on.



**Original Posted Date**: 2009-04-30T18:30:45.237-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:26:50.427-07:00

**Comment by lextm** [comment]
The actual decoding process of complex data types requires MIB documents and some custom code.

Since we introduced #SNMP Pro, this kind of issues can be resolved by the `IDecoder` interface. More information can be found in https://docs.lextudio.com/blog/snmp-pro-dateandtime-syntax-support-e99abc51bc2f
