### ISSUE TITLE
Creation of MIB files

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#415]
First of all, congratulations for the very execellent job done writing this
library. It looks like very promising and well written.  
  
I'd like to adopt the library for one of my next projects (right now I'm still
using the snmp_pp library in c++) however i'd like to know if you plan to add
to the project the feature to write custom MIB tree to a file or if you think
this could be already possibile using the current version of the library (or
tweaking it a little).  
I tried to navigate through the code but I found no hints.  
  
Many thanks.  

**Original Reported Date**: 2008-09-14T08:29:13.457-07:00
**Original CodePlex Discussion Thread ID**: 35638

**Comment by lextm** [comment]
These advanced features were included in #SNMP Pro, https://pro.sharpsnmp.com.
