### ISSUE TITLE
Sending data using SNMP Traps

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#417]
Hello,

I've been asked to send error codes and messages to a third party by use of
SNMP Traps. I'm new to this but after a bit of searching I came across your
excellent library. Unfortunately I know very little about Traps, even after
reading all I can find on the internet. I've been playing around with the
"Messenger.SendTrapV2" function and seem to be getting somewhere. I need to
send two strings, one which contains an error code and the second a brief
description of the problem. I'm guessing that I can put this in the
"variables" section? If so, is it possible to post a code snippet on how this
is done or is there some code in one of the tests that does this?

**Original Reported Date**: 2010-01-12T08:57:54.71-08:00
**Original CodePlex Discussion Thread ID**: 80573

**Comment by lextm** [comment]
The samples already covered that.
