### ISSUE TITLE
OID Description

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#445]
I should use Messenger.Walk to get all OIDs, but how can i get a description
of each OID ? Is there a method that returns a description ?

**Original Reported Date**: 2012-11-08T07:49:00.553-08:00
**Original CodePlex Discussion Thread ID**: 402419

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

As I commented on CodeProject, http://www.codeproject.com/Messages/4423847/Re-
MIB-Walk.aspx

Generally speaking, SNMP protocol does not cover that. An OID can legally have
no description at all in the MIB documents, while any SNMP agent does not
expose such descriptions in SNMP packet.  
  
You need to obtain the SNMP MIB documents from the vendor and then manually
translate each OID to an entity definition in one of the MIB documents.  
  
A MIB compiler might make it simpler, by removing the manual translation part.
But at this moment (#SNMP 7.5), #SNMP MIB compiler is not yet capable of doing
that.

-Lex  



**Original Posted Date**: 2012-11-09T19:40:29.477-08:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T04:10:13.463-07:00

**Comment by lextm** [comment]
Fully supported in #SNMP Pro, https://pro.sharpsnmp.com.
