### ISSUE TITLE
Trouble getting MAC addresses

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#450]
Hi,  
  
I'm having a hard time getting MAC addresses from a router.  
  
I'm using similar code to TestGet.cs:  
  
        Manager manager = new Manager();  
        try  
        {  
            Variable test = new Variable(new ObjectIdentifier(new uint[] { 1, 3, 6, 1, 2, 1, 4, 22, 1, 2, 10, 192, 168, 1, 10 }));  
            Variable variable = manager.Get(VersionCode.V2, IPAddress.Parse("192.168.0.10"), "public", test);  
            Console.WriteLine(variable.Data);  
        }...  
  
  
This is supposed to print "0:90:4b:e5:ad:85" but instead it prints "\0?K???".
I've tried getting the same OID with Net-SNMP and it returns the correct
value.  
  
Any ideas?  
  
  
Thanks,  
-Trev  
  

**Original Reported Date**: 2008-07-21T13:59:13.45-07:00
**Original CodePlex Discussion Thread ID**: 31938

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi, it is possible because #SNMP treats the physical address as normal
strings. It can be fixed. I am going to reproduce this on my dev machine to
see if there is an easy way to extract physical address in a meaning format.
Once I have done, I'll post an update here.  



**Original Posted Date**: 2008-07-21T22:23:21.963-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi, .NET Framework has a specific class for MAC addresses called
PhysicalAddress. So a new method is added in OctetString.cs in Change Set
14893. Now you can get a PhysicalAddress instance from it by calling
ToPhysicalAddress.  
  
However, this method may returns null if the OctetString instance is not a
valid MAC address.  
  
-Lex  



**Original Posted Date**: 2008-08-06T01:04:44.71-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:13:46.71-07:00

**Comment by lextm** [comment]
Similar to #412, the ultimate solution to identify and format special data types such as physical addresses is using #SNMP Pro.
