### ISSUE TITLE
Needed OID Description

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#459]
I am parsing the SNMPv-2 oid's for the sysUPTime while getting the description
from the DefaultObjectRegistry or SimpleObjectRegistry it shows that Entity
field is null and not showing descrption for the same while for the ifTable
oid it's showing the description.  
  
Can it be fixed/ feature added to the existing nugget package so that it can
be used..  

**Original Reported Date**: 2013-10-29T17:36:53.13-07:00
**Original CodePlex Discussion Thread ID**: 464143

**Comment by lextm** [comment]
Fully supported in #SNMP Pro, https://pro.sharpsnmp.com.
