### ISSUE TITLE
Does this library parses MIB trap types

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#467]
I have MIB file, which contains traps. Is there a way to get all the trap
information (trap types) from the MIB file?

Thanks,

Serg

**Original Reported Date**: 2011-01-12T11:47:25.83-08:00
**Original CodePlex Discussion Thread ID**: 241493

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

No, that's not yet supported.

Regards,

Lex



**Original Posted Date**: 2011-01-12T17:58:12.073-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Could you please confirm - Does the Compiler support the compilation TRAP-
TYPEs?  How far away is this likely to be?



**Original Posted Date**: 2011-01-28T01:29:34.547-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

I can confirm that compilation of TRAP-TYPEs is still incomplete in 6.0 and
6.1 release.

As one of our users contributed MIB parser/compiler improvements in this fork,

http://sharpsnmplib.codeplex.com/SourceControl/network/Forks/Nemo157/MIBParserUpdate

I plan to merge them to 7.0 branch next week. Only after the merge I can
reevaluate how far away we are from full compilation of such types.

Regards,

Lex



**Original Posted Date**: 2011-01-28T18:24:42.93-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

I am using version 7.5 of the library and it doesn't seem to parse TRAP-TYPE
clause, though I can see there are appropriate types defined and the grammar
has definitions also, as far as I can tell. I'm not familiar with ANTLR
though, nor I know where to look for bugs in the parser, if any. The MIB file
is confirmed to be correct, the parser doesn't report any errors either.

Could you provide any advice/comment on the problem? Am I missing anything?

Thanks,

Al.



**Original Posted Date**: 2012-06-08T06:59:26.727-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

After compiling the MIB document you should be able to access all basic types
via MibModule.Constructs. This is a collection of all parsed stuffs. To get
those modules, you need to first use SmiParser.GetDocument to compile the
file, and then access MibDocument.Modules.  

Currently only MibModule.Entities/Objects are used in other parts, which
matches the case for release 7.0 and below. In release 7.5 the plan is to be
API compatible with 7.0, while in release 8.0 we might expand the API set.

Regards,

Lex



**Original Posted Date**: 2012-06-09T19:55:11.537-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Thanks for your reply! Well, I suppose it's my mistake. The matter is that
trap-type`s aren't in Entities/Objects collections and I expected them to be
there (along with notifications and object definitions). I really should have
checked Constructs before posting, thanks again for pointing me there.

Regards,

Al.



**Original Posted Date**: 2012-06-12T23:21:45.81-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:18:13.753-07:00

**Comment by lextm** [comment]
Fully supported in #SNMP Pro, https://pro.sharpsnmp.com.
