### ISSUE TITLE
Constraining Request ID values?

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#474]
I have a device that has a known bug in its SNMP implementation, in that it
truncates request IDs to two bytes. This causes **Messenger.Get** to raise
exceptions as follows:

  * wrong response sequence: expected 927994154, received 4394 
  * wrong response sequence: expected 646947492, received 41636 

Indeed, if you AND the expected ID with 65535 (0xFFFF), you get the received
ID.

Despite the request ID mismatch, the device _is_ returning the correct data in
the PDU, as confirmed by Wireshark. However, since the call to
**Messenger.Get** raises an exception, I can't get at its return value (to get
to the variables), even if I catch the exception. If I could call
**Messenger.Get** and tell it to not compare the value of the returned request
ID and/or not raise an exception, that would be ideal, but I don't see a way
to do that.

So, since there is no hope of changing the device, I need a way to constrain
the request ID to <= 65535. However, **Messenger.NextRequestID** is read-only,
and I don't see an overload of **Messenger.Get** that takes a request ID
parameter.

I did see, in _Messenger.cs_ , where the limits of RequestCounter are set, so
I know that I can change the code there to constrain the request ID to 65535.
However, I'd rather not have to change the source, if possible; is there some
way of explicitly setting the request ID that I'm missing?

**Original Reported Date**: 2011-06-21T12:22:35.593-07:00
**Original CodePlex Discussion Thread ID**: 262222

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi,

Use GetRequestMessage directly is one of the choice. That allows you to
provide any parameters you like.

Messenger.cs is a simply wrapper over the *Message classes, so you can write
your own wrapper to replace it.

Regards,

Lex



**Original Posted Date**: 2011-06-24T05:09:31.833-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Thank you! I don't know how I missed **GetRequestMessage**. I'm using it to
constrain the request IDs to <= 65535, and everything works.



**Original Posted Date**: 2011-06-24T10:36:35.213-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T04:35:20.263-07:00

**Comment by lakecountypassage** [comment]
I just want to say THANK YOU! I was having the exact same issue and had no idea. You explained the issue perfectly and the fix works great. By chance, is this a Siemens M50 traffic signal controller?

My fix for anyone else that may have this issue:

`
        public static IList<Variable> GetPduResponse(string ip, string port, int timeout, List<Variable> variableList, string community = "public")
        {
            // Using this workaround https://github.com/lextudio/sharpsnmplib/issues/474

            IPEndPoint iPEndPoint = new IPEndPoint(IPAddress.Parse(ip), int.Parse(port));

            Random rand = new Random();
            int randomNumber = rand.Next(1, 65536);  // from 1 to 65535 inclusive
            var message = new GetRequestMessage(randomNumber, VersionCode.V1, new OctetString(community), variableList);
            var response = message.GetResponse(timeout, iPEndPoint);
            var pdu = response.Pdu();
            if (pdu.ErrorStatus.ToInt32() != 0)
            {
                throw ErrorException.Create(
                    "error in response",
                    iPEndPoint.Address,
                    response);
            }
            return pdu.Variables;
        }
`
