### ISSUE TITLE
Problem with HEX output

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#484]
Hi,  
  
I want to get ARP table from te switch and here is my code.  
Unfortunately I am getting output as follow.  
On the right side I expect hex.  
  
How do I fix it?  
  
Many thanks! and it is indeed great library :)  
  
.1.3.6.1.2.1.3.1.1.2.10603.1.192.168.61.1 => ↨Y?^Y  
.1.3.6.1.2.1.3.1.1.2.10603.1.192.168.61.2 => ↨??♥?  
.1.3.6.1.2.1.3.1.1.2.11143.1.192.168.66.1 => ↨??♥?  
.1.3.6.1.2.1.3.1.1.2.11143.1.192.168.66.2 => ↨???→  
  

using System;  
using System.Net;  
using Lextm.SharpSnmpLib;  
using System.Text;  
using System.Collections.Generic;

class portmapping  
{

private static string GetArpTable(string ip)  
{  
// ARP Table: 1.3.6.1.2.1.3.1.1.2  
// 1, 3, 6, 1, 2, 1, 3, 1, 1, 2  
try  
{  
Console.WriteLine("Trying IP address " \+ ip.ToString() + "...");  
IList<Variable> list = new List<Variable>();  
try  
{  
Manager.Walk(VersionCode.V2, new IPEndPoint(IPAddress.Parse(ip), 161), new
OctetString("community"), new ObjectIdentifier(new uint[] { 1, 3, 6, 1, 2, 1,
3, 1, 1, 2 }), list, 60000, WalkMode.WithinSubtree);  
}  
catch (SharpSnmpException ex)  
{  
Console.WriteLine(ex.Details);  
return "BAD-1";

}  
catch (Exception e) {  
Console.WriteLine("GetIp funtion error --->>>");  
Console.WriteLine("Source: " \+ e.Source.ToString());  
Console.WriteLine("Source: " \+ e.Message.ToString());  
return "BAD-2";  
}

foreach (Variable v in list)  
{  
Console.WriteLine(v.Id.ToString() + " => " \+ v.Data.ToString());  
}  
return "GOOD";  
}  
catch (SharpSnmpException ex)  
{  
if (ex is SharpOperationException)  
{  
Console.WriteLine("SharpSnmpException error --->>>");  
Console.WriteLine((ex as SharpOperationException).Details);  
}  
else  
{  
Console.WriteLine("SharpSnmpException error --->>>");  
Console.WriteLine(ex);  
}  
return "N/A";  
}  
}

private static string GetIp(string resolvename)  
{  
try {  
IPHostEntry hostInfo = Dns.GetHostEntry(resolvename);  
IPAddress[] address = hostInfo.AddressList;  
// Get the alias names of the addresses in the IP address list.  
String[] alias = hostInfo.Aliases;  
//Console.WriteLine(address[0]);  
return address[0].ToString();  
} catch (Exception e) {  
Console.WriteLine("GetIp funtion error --->>>");  
Console.WriteLine("Source: " \+ e.Source.ToString());  
Console.WriteLine("Source: " \+ e.Message.ToString());  
return "N/A";  
}  
}

// get system.sysLocation on localhost  
static void Main(string[] args)  
{  
string switchname = "switch01";  
string ip = GetIp(switchname);  
string arptable = GetArpTable(ip);  
Console.WriteLine(arptable);  
Console.WriteLine("Press any key to exit...");  
Console.Read();

}  
}

**Original Reported Date**: 2009-02-11T11:50:57.287-08:00
**Original CodePlex Discussion Thread ID**: 46865

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Found solution...  
Add extra function:  
  

private static string ConvertToHex(string asciiString)  
{  
string hex = "";  
asciiString = asciiString.ToLower();  
int i = 0;  
foreach (char c in asciiString)  
{  
if (i == 4)  
{  
hex += ".";  
i = 0;  
}  
hex += c.ToString();  
i++;

}  
return hex;  
}

  
  
  



// Getting MAC address





OctetString octstr = (OctetString)v.Data;





string macaddress = ConvertToHex(octstr.ToHexString());  
  
  
  





**Original Posted Date**: 2009-02-11T13:51:32.607-08:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:06:05.71-07:00

**Comment by lextm** [comment]
Related to # 412.
