### ISSUE TITLE
Parsing for Notification-/Trap Objects

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#491]
Hey there, I need for my project the possibility to parse a MIB-File for
Notification-Objects. That is no Problem when the objects, in the MIB-File,
are declared with NOTIFICATION-TYPE... but they won't be parsed when they are
declared with TRAP-TYPE, right? How can I do that? I just need, the names of
the NOTIFICATION-/TRAP-Type objects. And an other question, is there a way, to
get the variables of the objects with your parser? For Example:
ccmCallManagerFailed NOTIFICATION-TYPE OBJECTS { ccmAlarmSeverity,
ccmFailCauseCode } I get the name ("ccmCallManagerFailed") but how can I get
the variables ("ccmAlarmSeverity", "ccmFailCauseCode")? Thank you for help
Very nice project! Best regards Philipp

**Original Reported Date**: 2010-04-29T00:14:27.727-07:00
**Original CodePlex Discussion Thread ID**: 210957

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

We already have TRAP-TYPE parsing capability in the compiler.

Once compiled, you can access TrapType objects listed in IModule.Entities.

We don't parse "OBJECTS" property for NOTIFICATION-TYPE/TRAP-TYPE yet, but you
can feel free to add such a feature to NotificationType or TrapType.

Our parser implementation is not yet finished, so patches are welcome.

Regards,

Lex



**Original Posted Date**: 2010-04-29T16:54:28.24-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi Lex Thank you for you answer! But there are no TRAP-TYPE objects. Just the
identifier which is defined in the ENTERPRISE - Attribute. If I will extend
your Parser I will send you the source code! Regards, Phil



**Original Posted Date**: 2010-04-29T23:58:22.58-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T20:51:59.39-07:00

**Comment by lextm** [comment]
Fully implemented in #SNMP Pro, https://pro.sharpsnmp.com.
