### ISSUE TITLE
How to convert OctetString type to BitString type

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#499]
Hi,  
Thanks for the great library.  
  
I am new for c# and snmp programming.  
  
Now i am working on a project with c# and snmp knowledges . when i use this
library , i have a problem that "How can i convert variables of OctetString
type to BitString type"?  
  
i had spent hours on it but failed.  
  
thanks for any answers.  
  
cool

**Original Reported Date**: 2009-01-14T01:19:35.29-08:00
**Original CodePlex Discussion Thread ID**: 44161

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hello,

  

If you mean how to convert an OctetString object to BitString, you have to

  

1\. Expose OctetString._raw as a public or internal so you can access the data
in raw bytes. For example, add the following code there,

  

public byte[] GetRaw()

{

retutrn (byte[])_raw.Copy();

}

  

2\. Create a BitString object with BitString(byte[] raw). Pass in the raw
bytes we get from step 1.

  

In this way you can start using the BitString object as it contains the same
data of the original OctetString object. If now you understand the logic, I
believe you notice that it is easy to do the opposite.

  

Sorry that I never explicitly tell this secret of _raw. I will write about it
later in a blog post.

  

-Lex



**Original Posted Date**: 2009-01-16T22:38:25.543-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi, Lex  
  
Thanks for your help, but i still have problems.  
  
i read from BitString.cs that BitSting(byte[] raw) has the following line:  
  
for (int j = 0; j < _size; j++)  
{  
_bits[j] = (raw[4 * j] << 24) | (raw[(4 * j) + 1] << 16) | (raw[(4 * j) + 2] << 8) | raw[(4 * j) + 3];  
}  
  
In my case, _raw from my OctetString object has only two elements , say it
rawByte[0], rawByte[1],  
  
when i creat a BitSring object with BitString(byte[] raw) ,and Pass in the raw
bytes rawByte, it failed. (bitstring is 32 bits less, should turn it into a
32-bit INTEGER ?)  
  
when i simply add two more bytes initialize with 0 to it . sometimes i can get
the right answers ,  
but sometimes failed(one case is rawByte[0] =128, rawByte[1]= 32).  
  
\--------------------------------------------------------------------------  
here is part of my code:

byte[] bitmapData = ((OctetString)table_bitmap[row, 0].Data).GetRaw();  
BitString bitstring = new BitString(new byte[] { bitmapData[0], bitmapData[1],
0, 0 });

for (int i = 0; i < 16; i++)  
{  
if (bitstring[i])  
arrlist.Add(bitmapValues[i]);  
}

\-------------------------------------------------------------------  
  
  
By the way, i find that the results from gettable is not in order , i change a
little bit in Manager.cs as bellow  
\------------------------------  

IList<Variable> list = new List<Variable>();  
int **cols** = SteveWalk(version, endpoint, community, table, list, timeout,
WalkMode.WithinSubtree);  
  
// int rows = Walk(version, endpoint, community, table, list, timeout,
WalkMode.WithinSubtree);  
if (**cols** == 0)  
{  
return new Variable[0, 0];  
}

**int rows = list.Count /cols ;  
** int k = 0;  
Variable[,] result = new Variable[rows, cols];

for (int j = 0; j < cols; j++)  
{  
for (int i = 0; i < rows; i++)  
{  
result[i,j] = list[k];  
k++;  
}  
}

return result;

\------------------  
it can return an ordered table for me .  
  
Can you help me ?  
  
-cool  
  
  
  
  
  



**Original Posted Date**: 2009-01-18T21:01:17.453-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi, Lex  
  
My problem has been solved , Thank you .  
  
I just change the code bellow a little bit.  
\--------------------------------------------------------  

public BitString(byte[] raw)  
{  
if (raw == null)  
{  
throw new ArgumentNullException("raw");  
}  
  
if (raw.Length == 0)  
{  
throw new ArgumentException("raw cannot be empty.", "raw");  
}

**** _nbits = **raw.Length * 8;// -raw[0];** // 8.6.2  
_size = (_nbits + 31) / 32;  
_bits = new int[_size];  
for (int j = 0; j < _size; j++)  
{  
_bits[j] = (raw[4 * j] << 24) | (raw[(4 * j) + 1] << 16) | (raw[(4 * j) + 2] << 8) | raw[(4 * j) + 3];  
}  
  
_raw = raw;  
_bytes = ByteTool.ToBytes(SnmpType.BitString, _raw);  
}  
\----------------------------------------  
  
  
-cool

  



**Original Posted Date**: 2009-01-19T17:10:26.187-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi cool,  
  
Thanks for sharing your code. I think I need to spare some time before 2.0
release to review BitString class. I mainly use Malcolm's code without
changes. It seems that this class needs some update later.  
  
-Lex 



**Original Posted Date**: 2009-01-25T06:10:19.917-08:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:43:17.227-07:00

**Comment by lextm** [comment]
BITS related complex data types are only fully supported in #SNMP Pro. Related to #412.
