### ISSUE TITLE
How to diffrentiate  Device type in snmp

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#511]
hi,  
first thanks for this awesome library,  
  
I am using Get method for retrieving device information.  
  
i found below concept from internet : -  
  
Switch :-  
If the device is a Switch, it should respond for the OID
".1.3.6.1.2.1.17.1.2.0" and ".1.3.6.1.2.1.4.1.0" value will be 2.  
  
Router:-  
If the device is a Router, it should respond the OID ".1.3.6.1.2.1.4.1.0"
value as 1.  
  
Printer :-  
If the device is Printer, it should respond for the OID
".1.3.6.1.2.1.43.5.1.1.1.1" .  
  
Now, my problem is when i query 1.3.6.1.2.1.4.1.0 then it's returning 2 that's
is switch (according to concept), but that is not a switch . it's actually
other device like UPS or power transmission unit or modem.  
  
in this condition how can i identify network device type ?  
  
if there is any other way to find device type like
server,workstation,router,switch,printer,smart phones, power transmission
unit,bridge and so on.  
  
Thanks in Advance.  

**Original Reported Date**: 2014-02-26T05:03:30.013-08:00
**Original CodePlex Discussion Thread ID**: 535627

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

The discussion board is going to be shut down by March 31 2014.  
  
New posts won't be monitored and answered.  
  
If you have any question about #SNMP, please go to StackOverflow and use
sharp-snmp tag.  



**Original Posted Date**: 2014-02-26T18:46:10.843-08:00

**Comment by lextm** [comment]
#SNMP Library can only handle the protocol itself, so the responsibility to detect device types is up to the SNMP applications themselves. Thus, no answer can be provided here.
