### ISSUE TITLE
Assembler very slow

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#512]
Isn't it possible to create a much faster assembler?

**Original Reported Date**: 2012-07-02T13:37:33.153-07:00
**Original CodePlex Discussion Thread ID**: 361734

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

It is possible to make it faster (by compiling MIB documents to special module
files - database files, and then use the module files when compiling further
MIB documents). Currently the assembler completely compiles all MIB documents,
which wastes lots of time.

But since I did not have time recently, it is not improved since 2008.



**Original Posted Date**: 2012-07-03T02:01:37.07-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

The assembler can be made faster, but this has been implemented only in Pro
Edition,  
  
<https://sharpsnmplib.codeplex.com/wikipage?title=Pro%20Edition>  



**Original Posted Date**: 2014-02-01T04:01:23.913-08:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:32:12.757-07:00

**Comment by lextm** [comment]
Significantly improved in #SNMP Pro, https://pro.sharpsnmp.com.
