### ISSUE TITLE
MIB Parsing

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#521]
Hi there,

This project is fantastic! The code is professional and the included MIB
browser showcases it magnificently. Well done!

Given the full path to a MIB and an OID defined therein, I'm trying to extract
the name and SNMP type (SYNTAX ) of the object. Is this possible? Though new
to the project, I've tried for several hours. Any code snippets would be
greatly appreciated!

Thank you,

Ben

**Original Reported Date**: 2009-11-21T22:40:17.98-08:00
**Original CodePlex Discussion Thread ID**: 75845

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi Ben,

It should be possible if we enhance the existing compiler, but now I rather
spare time on the new ANTLR based compiler. It is still far to go there.

If you like, you can check out the latest source code and play with our AST
project.

Regards,



**Original Posted Date**: 2009-11-22T01:19:16.187-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi Lex,

Okay. Thank you so much - both for the great project and the prompt help!

Cheers,

Ben



**Original Posted Date**: 2009-11-22T12:55:15.78-08:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:45:10-07:00

**Comment by lextm** [comment]
Fully implemented in #SNMP Pro, https://pro.sharpsnmp.com.
