### ISSUE TITLE
Walking on MIB IF-MIB interfaces

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#569]
Hi there!  
  
I'm tring for the first time this #SNMP Suite.  
  
To test this tool I'm using NetSNMP to compare the results. I've notice that
when I try to get the Physical Interfaces (1.3.6.1.2.1.2.2.1.6.*) it always
gives me an empty value, but in NetSNMP it is returning the correct values.  
  
Using the NET-SNMP I get:  
  
_IF-MIB::ifPhysAddress.2 = STRING: 0:c:29:71:86:17  
IF-MIB::ifPhysAddress.3 = STRING: 0:c:29:71:86:21  
IF-MIB::ifPhysAddress.4 = STRING: 0:c:29:71:86:2b_  
  
Using #SNMP I get:  
_  
Variable: Id: .1.3.6.1.2.1.2.2.1.6.1; Data:  
Variable: Id: .1.3.6.1.2.1.2.2.1.6.2; Data:  
Variable: Id: .1.3.6.1.2.1.2.2.1.6.3; Data:  
Variable: Id: .1.3.6.1.2.1.2.2.1.6.4; Data:  
  
_  
I'm using the TwinTower release on a .net 2.0 environment.  
  
BR  

**Original Reported Date**: 2008-11-16T11:08:21.177-08:00
**Original CodePlex Discussion Thread ID**: 40045

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

No feed-backs? Only me have detected the problem? :(  
  
  



**Original Posted Date**: 2008-11-18T17:02:40.99-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

I actually just got done retrieving the MAC address from the MIB-II Interfaces
table.  
  
Here is the basic approach with the latest release which I don't know the name
or version:  
  
Variable variable = new Variable(new
ObjectIdentifier(Common.StringToUint(".1.3.6.1.2.1.2.2.1.6.7")));  
Variable result = m_snmpManager.GetSingle(IPAddress.Parse(m_host),
m_community, variable);  
((OctetString)result.Data).ToPhysicalAddress().ToString()  
  
I hope that helps.  



**Original Posted Date**: 2008-11-19T09:32:29.83-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hello,  
  
I found that the problem is with the implementation of the toString() in the
Variable object method that doesn't handle correctly with the PhysicalAddress
type.



**Original Posted Date**: 2008-11-20T08:29:35.387-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

I have noticed some issues where toString() doesn't handle the information
correctly. Would you mind adding an issue to the issue tracker? It would be a
great help. I will see if I can get to it this weekend! Or Bug Lex into
looking at it.  



**Original Posted Date**: 2008-11-20T14:06:30.057-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

No prob.  
I've just posted the issue.  



**Original Posted Date**: 2008-11-20T14:25:04.923-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi, thanks for logging this issue. But I'd like to state some details here and
provide you an estimate about when we can fix it.

  

If you notice, Net-SNMP output directly shows you the name of the objects,
which means that it reads the MIB documents and finds out this is physical
address. That's why it smartly interprets those raw bytes to nice looking MAC
address for you.

  

However, at this moment, #SNMP is not able to parse MIB documents that
further, so you have to use the workaround mentioned by brianb. Yes, that
means you have to convert the bytes to physical address yourself.

  

Therefore, unless the parser is enhanced, this issue cannot be resolved
easily. :)

  

-Lex



**Original Posted Date**: 2008-11-21T17:24:29.847-08:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:09:48.31-07:00

**Comment by lextm** [comment]
Fully implemented in #SNMP Pro, https://pro.sharpsnmp.com.
