### ISSUE TITLE
Loading MIB file

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#575]
Hi Lextm,  
  
I have a MIB document that I would like to load.  Could you please advise how
to do this?  
  
A similar question like this was answered as:  If you have MIB documents
(*.mib or *.txt), please take a look at ObjectRegistry class. The comments
inside can tell you which method is suitable.  
  
However there are so many methods and not easy to determine which one to pick.
Any extra help will be much appreciated.  
  
Thanks,  
  
xplorer2k  
  

**Original Reported Date**: 2009-04-16T13:25:47.943-07:00
**Original CodePlex Discussion Thread ID**: 53560

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

There are only three methods available via IObjectRegistry interface to load
MIB documents,

  

/// <summary>

/// Loads a folder of MIB files.

/// </summary>

/// <param name="folder">Folder</param>

/// <param name="pattern">MIB file pattern</param>

void CompileFolder(string folder, string pattern);

  

/// <summary>

/// Loads MIB files.

/// </summary>

/// <param name="fileNames">File names.</param>

void CompileFiles(IEnumerable<string> fileNames);

  

/// <summary>

/// Loads a MIB file.

/// </summary>

/// <param name="fileName">File name</param>

void Compile(string fileName);

  

-Lex



**Original Posted Date**: 2009-04-17T19:04:35.16-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Thanks Lex,  
  
xplorer2k  
  



**Original Posted Date**: 2009-04-20T08:21:56.743-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

在MIB浏览器中，我怎样获取MIB节点的属性，比如此节点的类型，描述，是否只读等等～



**Original Posted Date**: 2009-04-28T17:28:27.987-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Well, I am going to translate rqx110's question to English so other visiters
can understand it.

  

The question is how to know a node's properties in MIB browser, such as type,
description, and so on.

  

Due to our current compiler implementation, such information is not extracted
from MIB documents, so now it is not possible to see it in the browser. We
plan to improve in 3.0 release.



**Original Posted Date**: 2009-04-30T18:33:10.88-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:26:44.297-07:00

**Comment by lextm** [comment]
Fully implemented in #SNMP Pro, https://pro.sharpsnmp.com.
