### ISSUE TITLE
How to map OID to its Description/value

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#577]
Hi,

    I wrote a trap listner and configured my device to send all traps to my listner IP address and i am able to receive all the traps in the form of OID.

Now how can i map it to MIB table/file. I need to know what is the description
of that particular OID. how can i do this...?

(Around 4 years back i did this by mapping the particulr OID to an already
defined XML through NetToolWork, but now there is no XML mapping)

\------------------

I explored in this regard and everyone are telling compile the MIB into
modules and then parse for a particular OID for its corresponding
description/valure.

so i need to do above steps for all OID i receives.. i dont think its feasible
solution.

\-----------------

I like to know,

1\. How can i map the received OID?

2\. What is the use of compiling the MIB?

3\. What is MIB module.

\--------------------------------

Any reply is greately appriciated.

Thanx

daya

**Original Reported Date**: 2010-03-03T19:44:23.14-08:00
**Original CodePlex Discussion Thread ID**: 203729

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

"Everyone" is right, because only parsing MIB documents can provide you that
information.

1\. #SNMP MIB Browser has a notification panel. This panel is a trap listener
reference design you can refer to, where I show how to map OID to textual form
using IObjectRegistry.

2\. You already know the usage. Compiling them can tell you more about each
objects.

3\. Different people have different views on MIB module. Generally speaking, a
MIB document (*.mib or *.txt) contains a MIB module or several modules. SMI
defines the details.

"Understanding SNMP MIBs" is the best book I found in this field, but there
are other books mentioning the definitions. If you have enough courage, the
IETF RFC documents are the origin of all information for you.

#SNMP does not yet have full support on this, as our compiler is not powerful
enough.

Regards,

Lex



**Original Posted Date**: 2010-03-06T01:38:01.567-08:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T20:53:17.5-07:00

**Comment by lextm** [comment]
Fully implemented in #SNMP Pro, https://pro.sharpsnmp.com.
