### ISSUE TITLE
How to get Data type (SnmpType) for an OID?

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#582]
I want to read from an SNMP agent.  I have successfully loaded MIB file and I
am able to find my respective MIBs using
DefaultObjectRegistry.Instance.Tree.Find("Module", mibName);

It returns an IDefinition object.  Is there a way I can know the data type (or
SnmpType) associated with it.  Meaning is it an OctetString, Counter32,
Integer32 or what?

Please help.

**Original Reported Date**: 2012-02-04T19:38:01.03-08:00
**Original CodePlex Discussion Thread ID**: 293452

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

For #SNMP 6 and 7, this is impossible.

In the upcoming 8 release, the new compiler will be capable of providing all
necessary information.

Regards,

Lex



**Original Posted Date**: 2012-02-05T01:22:34.423-08:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T20:38:53.88-07:00

**Comment by lextm** [comment]
Fully implemented in #SNMP Pro, https://pro.sharpsnmp.com.
