### ISSUE TITLE
SNMP Broadcast in IPv6

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#596]
Hi Lex,

I would like to implement the broadcast feature with IPv6 (using multicast
addresses, _ff02::1_).

Please let me know whether it is feasible to perform the same.

Currently when i try with the multicast address, its not working.

please help me knowing whether it is feasible.

Regards,

Preethi

**Original Reported Date**: 2010-04-13T10:02:14.537-07:00
**Original CodePlex Discussion Thread ID**: 209211

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

HI Preethi,

The IP v6 story is completely different from IP v4, so unless I have enough
time to visit that area, I cannot simply reply to you with a direct answer,
YES or NO.

Since you already have an IP v6 environment, and our source code is fully
available, please initiate an investigation on your own, or with your
teammates. If you happen to find a patch that works, you can share with me.

Regards,

Lex



**Original Posted Date**: 2010-04-13T18:53:16.483-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:23:38.61-07:00

**Comment by lextm** [comment]
Duplicate to #339
