### ISSUE TITLE
How to get syntax of a field

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#672]
Hello,

I'm using SharpSnmpLib to listen for traps and it work good. However i could
not find how to find syntax of an object - for a given leaf OID I need to get
syntax of it - whether it's Integer32, ObjectIdentifier, or Counter64, etc.

I can do it when I have trap by checking type of Data property of a variable.
But in my case i need to get type before trap arrives (read trap ids from
configuration and check their types from loaded MIB modules).

What is the easiest way to achieve this?

Thank you

**Original Reported Date**: 2012-04-24T07:53:38.393-07:00
**Original CodePlex Discussion Thread ID**: 353377

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

There is no easy way right now. For #SNMP 6/7, the MIB compiler cannot extract
such information from MIB documents.

We are currently working on #SNMP 8, where a new compiler will be written to
fill this gap.

Regards,

Lex



**Original Posted Date**: 2012-04-27T18:21:06.327-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T04:14:26.763-07:00

**Comment by lextm** [comment]
Fully implemented in #SNMP Pro, https://pro.sharpsnmp.com.
