### ISSUE TITLE
Acknowledge Traps/Informs?

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#679]
I am about to start a project that will require a trap listener. The
requirement I received this morning included this statement: "We are planning
to send InformRequests. An InformRequest requires an ACK. It also requires
configuration of the SNMPv3 user on the inform receiver."

Does the #SNMP library support this [yet]?

Thanks!

Mike

**Original Reported Date**: 2010-06-04T10:19:26.34-07:00
**Original CodePlex Discussion Thread ID**: 215008

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi Mike,

#SNMP supports all except "It also requires configuration of the SNMPv3 user
on the inform receiver.".

You can use Browser.exe and snmpd.exe to test it out,

1\. Open Browser.exe, and click Disabled button on Notification panel so it
monitors incoming messages.

2\. Open snmpd.exe and click Send Inform button to send out a test message.

SNMP v3 INFORM is a bit hard to fulfill in 5.0 release, so I am still
researching on how to add it in 6.0 release.

Regards,



**Original Posted Date**: 2010-06-04T19:20:23.69-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

So what happens when an inform is received? It appears that they're simply not
getting to me. I built the latest code from svn last night. I can send the
following commands from a local Linux box successfully:

  * snmptrap -v3 -u mike -c public 192.168.56.1 0 1.3.6.1.6.3.1.1.5.3
  * snmptrap -v2c -u mike -c public 192.168.56.1 0 1.3.6.1.6.3.1.1.5.3
  * snmptrap -v2c -c public 192.168.56.1 0 1.3.6.1.6.3.1.1.5.3

They are each treated identically as a V2 trap.

These commands work, and each is interpreted as an Inform:

  * snmptrap -v2c -Ci -c public 192.168.56.1 0 1.3.6.1.6.3.1.1.5.3
  * snmpinform -v2c  -c public 192.168.56.1 0 1.3.6.1.6.3.1.1.5.3

What doesn't work is the the following:

  * snmptrap -v3 -Ci -c public 192.168.56.1 0 1.3.6.1.6.3.1.1.5.3 
  * snmpinform -v3  -c public 192.168.56.1 0 1.3.6.1.6.3.1.1.5.3

Both commands report a timeout on the sender. Am I not setting something up
correctly, or is it simply not supported? Personally, I don't care if the user
parameter is ignored for now; I just want to hit my trap handler. I'll fudge
the whole user thing for now, as it's a minor issue.

Thanks!

Mike



**Original Posted Date**: 2010-06-05T10:00:04.123-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Ah, OK. That is _exactly_ the behavior I'm seeing. I will see if the client
can do v2 informs, since they're really only concerned with knowing the
message was received. Thanks for the clarification!

Mike



**Original Posted Date**: 2010-06-05T19:45:19.187-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T21:33:57.123-07:00

**Comment by lextm** [comment]
Inform support was implemented in #207.
